import Config

config :greenhouse_tycoon, GreenhouseTycoon.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "your_username",
  password: "your_password",
  database: "greenhouse_tycoon_prod",
  hostname: "your_hostname",
  pool_size: 20

# Individual apps configure their own ExESDB instances for production

# Configure ExESDB for greenhouse_tycoon production
config :greenhouse_tycoon, :ex_esdb,
  store_id: :greenhouse_tycoon_prod,
  data_dir: "/data/greenhouse_tycoon_prod",
  pub_sub: :ex_esdb_pubsub,
  db_type: :cluster,
  timeout: 15_000,
  reader_idle_ms: 30_000,
  writer_idle_ms: 30_000

# Configure Commanded for greenhouse_tycoon production
config :greenhouse_tycoon, GreenhouseTycoon.CommandedApp,
  event_store: [
    adapter: ExESDB.Commanded.Adapter,
    store_id: :greenhouse_tycoon_prod,
    stream_prefix: "greenhouse_tycoon_prod_",
    serializer: Jason,
    event_type_mapper: GreenhouseTycoon.EventTypeMapper
  ]

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :greenhouse_tycoon_web, GreenhouseTycoonWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, :api_client, GreenhouseTycoon.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
